### ISSUE TITLE
Your answer shouldn't be right

### ISSUE THREAD

**Issue by sdegutis** [garybernhardt/preact-typescript-component-wont-build#2]
According to the .d.ts file in your repo, [h() takes a string as its first argument](https://github.com/garybernhardt/preact-typescript-component-wont-build/blob/b456b4dc29c1c32339d6e0c6f34d24e8cd189b9c/src/preact-8.2.9.min.d.ts#L109-L110).

So it should never work. I don't see why changing what you pass as the second argument would affect this. It might make sense if there were overloaded type definitions for h(), but there aren't.

**Comment by MartinJohns** [comment]
According to the .d.ts file in his repo, [h() also takes a component factory as its first argument](https://github.com/garybernhardt/preact-typescript-component-wont-build/blob/b456b4dc29c1c32339d6e0c6f34d24e8cd189b9c/src/preact-8.2.9.min.d.ts#L104).

**Comment by sdegutis** [comment]
Oops yeah my bad.
